apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: postgres-claim
    namespace: django-space
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  namespace: django-space
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi
  volumeName: postgres-volume
