apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
spec:
  storageClassName: nfs
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.196
    path: "/mnt/nfs_share/DB"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: postgres-claim
    namespace: django-space
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  namespace: django-space
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi
  volumeName: postgres-volume