apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-kube
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 198.168.0.196
    path: /mnt/nfs_share
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: nfs-claim
    namespace: apps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: nfs-kube
