apiVersion: v1
kind: Service
metadata:
  namespace: django-space
  name: django-service
spec:
  selector:
    app: django
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort : 31313
